name: miniRT CI

on: [push, pull_request]

jobs:
  norminette-job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v4
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
  tests:
    runs-on: ubuntu-latest
    name: test-parser
    steps:
        - uses: actions/checkout@v4
        - name: Parser test
          run: make min-test
